// flow-typed signature: d9c056cd6802b6c1bea0f136efeb8911
// flow-typed version: <<STUB>>/react-navigation-material-bottom-tabs_v^1.0.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-material-bottom-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-material-bottom-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-material-bottom-tabs/dist/index' {
  declare module.exports: any;
}

declare module 'react-navigation-material-bottom-tabs/dist/navigators/createMaterialBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-material-bottom-tabs/src/index' {
  declare module.exports: any;
}

declare module 'react-navigation-material-bottom-tabs/src/navigators/createMaterialBottomTabNavigator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-material-bottom-tabs/dist/index.js' {
  declare module.exports: $Exports<'react-navigation-material-bottom-tabs/dist/index'>;
}
declare module 'react-navigation-material-bottom-tabs/dist/navigators/createMaterialBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-material-bottom-tabs/dist/navigators/createMaterialBottomTabNavigator'>;
}
declare module 'react-navigation-material-bottom-tabs/src/index.js' {
  declare module.exports: $Exports<'react-navigation-material-bottom-tabs/src/index'>;
}
declare module 'react-navigation-material-bottom-tabs/src/navigators/createMaterialBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-material-bottom-tabs/src/navigators/createMaterialBottomTabNavigator'>;
}
